language: node_js
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '4'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
install:
  - npm install -g codecov
script:
  - npm run cobertura
  - codecov
