language: node_js
notifications:
  email: false
node_js:
  - '8'
  - '6'
  - '4'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_script:
  - npm install -g codecov
script:
  - npm run test:unit
  - codecov
